apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "codezero.name" . }}-orchestrator-binding
subjects:
- kind: ServiceAccount
  name: {{ include "orchestrator.name" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: orchestrator-clusterrole
  apiGroup: rbac.authorization.k8s.io