apiVersion: v1
kind: Service
metadata:
  name: {{ include "orchestrator.name" . }}
  labels:
    {{- include "orchestrator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8900
      targetPort: 8900
      protocol: TCP
      name: http
  selector:
    {{- include "orchestrator.selectorLabels" . | nindent 4 }}
