apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "codezero.name" . }}-system-cluster-binding
subjects:
- kind: ServiceAccount
  name: {{ include "system.name" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: system-clusterrole
  apiGroup: rbac.authorization.k8s.io
