apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "codezero.name" . }}:system
rules:
- apiGroups: [""]
  resources: ["services", "pods"]
  verbs: ["get", "watch", "list", "patch", "create", "delete"]
- apiGroups: ["discovery.k8s.io"]
  resources: ["endpointslices"]
  verbs: ["list", "watch"]
- apiGroups: ["routing.codezero.io"]
  resources: ["serves"]
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
