{{- if ne .Release.Namespace "codezero" }}
{{- fail "The codezero system has to be installed in codezero namespace" }}
{{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "system.fullname" . }}
  labels:
    {{- include "system.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.system.replicaCount }}
  selector:
    matchLabels:
      {{- include "system.selectorLabels" . | nindent 6 }}
      {{- include "codezero.externalLBSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.system.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "system.selectorLabels" . | nindent 8 }}
        {{- include "codezero.externalLBSelectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "system.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.system.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "system.name" . }}
          securityContext:
            {{- toYaml .Values.system.securityContext | nindent 12 }}
          image: "c6oio/czsystem:{{ .Values.system.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.system.image.pullPolicy }}
          env:
            - name: CZ_SPACE_CA_CERT
              value: /etc/ssl/certs/space/ca.pem
            - name: CZ_SPACE_CERT
              value: /etc/ssl/certs/space/tls.pem
            - name: CZ_SPACE_CERT_KEY
              value: /etc/ssl/certs/space/tls.key
            - name: CZ_ORCHESTRATOR_HOST
              value: "{{ include "orchestrator.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:8900"
          envFrom:
            - secretRef:
                name: {{ include "system.fullname" . }}
          ports:
            - containerPort: 443
              protocol: TCP
          resources:
            {{- toYaml .Values.system.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/ssl/certs/space
              name: space-cert
              readOnly: true
      volumes:
        - name: space-cert
          secret:
            secretName: space-cert
            optional: true
      {{- with .Values.system.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.system.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.system.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
