apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "system.name" . }}
  labels:
    {{- include "system.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.system.replicaCount }}
  selector:
    matchLabels:
      {{- include "system.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "system.podAnnotations" . | nindent 8 }}
      labels:
        {{- include "system.podLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "system.name" . }}
      securityContext:
        {{- toYaml .Values.system.podSecurityContext | nindent 8 }}
      initContainers:
        - name: space-init
          image: "c6oio/spaceinit:955bf44"
          imagePullPolicy: {{ .Values.system.image.pullPolicy }}
          env:
            - name: CZ_CLUSTER_CERT
              value: /etc/ssl/certs/space/tls.pem
            - name: CZ_CLUSTER_CERT_KEY
              value: /etc/ssl/certs/space/tls.key
            {{- if .Values.hub.url }}
            - name: CZ_HUB_URL
              value: {{ .Values.hub.url }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "system.name" . }}
          volumeMounts:
            - mountPath: /etc/ssl/certs/space
              name: space-cert
              readOnly: true
        - name: wait-for-orchestrator
          image: public.ecr.aws/docker/library/busybox:1.36
          command: ["sh", "-c", "for i in {1..20}; do if wget --spider --quiet 'http://orchestrator:8900'; then exit 0; fi; sleep 0.5; done; exit 1"]
      containers:
        - name: {{ include "system.name" . }}
          securityContext:
            {{- toYaml .Values.system.securityContext | nindent 12 }}
          image: "c6oio/system:{{ .Values.system.image.tag | default .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.system.image.pullPolicy }}
          env:
            - name: CZ_SPACE_CA_CERT
              value: /etc/ssl/certs/space/ca.pem
            - name: CZ_CLUSTER_CERT
              value: /etc/ssl/certs/space/tls.pem
            - name: CZ_CLUSTER_CERT_KEY
              value: /etc/ssl/certs/space/tls.key
            {{- if .Values.hub.url }}
            - name: CZ_HUB_URL
              value: {{ .Values.hub.url }}
            {{- end }}
            - name: CZ_SPACE_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "codezero.name" . }}
                  key: spaceID
                  optional: true
            - name: CZ_ORCHESTRATOR_AUTHORITY
              value: "{{ include "orchestrator.name" . }}.{{ .Release.Namespace }}:8900"
            - name: CZ_PORT
              value: "8800"
            - name: CZ_ROUTER_IMAGE
              value: "c6oio/router:{{ .Values.system.image.tag | default .Values.image.tag | default .Chart.AppVersion }}"
          envFrom:
            - secretRef:
                name: {{ include "system.name" . }}
          ports:
            - containerPort: 8800
              protocol: TCP
          resources:
            {{- toYaml .Values.system.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/ssl/certs/space
              name: space-cert
              readOnly: true
      volumes:
        - name: space-cert
          secret:
            secretName: space-cert
            optional: true
      {{- with .Values.system.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.system.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.system.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
