apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: system-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["patch"]