apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "codezero.name" . }}-system-binding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "system.name" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: system-role
  apiGroup: rbac.authorization.k8s.io
