{{- if and (eq .Values.space.token "") (.Release.IsInstall) }}
{{- fail "A Values.token is required" }}
{{- end }}


{{- define "codezero.spaceToken" -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (include "system.name" .) -}}
{{- if $existingSecret -}}
{{ $existingSecret.data | toYaml }}
{{- else -}}
CZ_HUB_SPACE_TOKEN: {{ .Values.space.token | b64enc }}
{{- end -}}
{{- end -}}


apiVersion: v1  
kind: Secret
metadata:
  name: {{ include "system.name" . }}
data:
{{ include "codezero.spaceToken" . | indent 2 -}}