{{- if .Values.system.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "system.name" . }}
  labels:
    {{- include "system.labels" . | nindent 4 }}
  {{- with .Values.system.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
