apiVersion: v1
kind: Service
metadata:
  name: {{ include "system.fullname" . }}
  labels:
    {{- include "system.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
      name: system
  selector:
    {{- include "system.selectorLabels" . | nindent 4 }}
