# Default values for CodeZero.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

image:
  tag: pasley
hub:
  url: https://api.codezero.io
space:
  token: ""

podAnnotations: { }
labels: { }
podLabels: { }

system:
  name: system
  image:
    tag: ""
    pullPolicy: Always
  replicaCount: 1

  podAnnotations: { }
  labels: { }
  podLabels: { }

  podSecurityContext: { }
  securityContext: { }

  resources: { }
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }

  serviceAccount:
    create: true
    annotations: { }
    name: ""

orchestrator:
  name: orchestrator
  image:
    tag: ""
    pullPolicy: Always
  replicaCount: 1

  podAnnotations: { }
  labels: { }
  podLabels: { }

  podSecurityContext: { }
  securityContext: { }

  resources: { }
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }

  serviceAccount:
    create: true
    annotations: { }
    name: ""

lb:
  name: lb
  image:
    tag: "2.8.1"
    pullPolicy: Always
  replicaCount: 1

  podAnnotations: { }
  labels: { }
  podLabels: { }

  podSecurityContext: { }
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    allowPrivilegeEscalation: true
    capabilities:
      drop:
        - ALL
      add:
        - NET_BIND_SERVICE
    seccompProfile:
      type: RuntimeDefault

  resources: { }
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }

  serviceAccount:
    create: true
    annotations: { }
    name: ""

  service:
    type: LoadBalancer