# Default values for Codezero.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  tag: 2.7.4
hub:
  url: https://hub.codezero.io
space:
  token: ""
  name: ""
org:
  apikey: ""
  id: ""
opa:
  url: ""
  enabled: false
tracing:
  enabled: false

podAnnotations: { }
labels: { }
podLabels: { }

router:
  privilegedAccess: false
  replicas: 1
  # ref: https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/
  topologySpreadConstraints: []

operator:
  name: operator
  image:
    tag: ""
    pullPolicy: Always
  replicas: 1

  podAnnotations: { }
  labels: { }
  podLabels: { }

  podSecurityContext: { }
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault

  nodeSelector: { }
  tolerations: [ ]
  affinity: { }

spaceagent:
  name: spaceagent
  image:
    tag: ""
    pullPolicy: Always
  replicas: 1

  # for horizontal scaling (experimental). Secret must be in the same namespace as the spaceagent
  redis:
    secret: ""

  podAnnotations: {}
  labels: {}
  podLabels: {}

  podSecurityContext: {}
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault

  # ref: https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/
  topologySpreadConstraints: []
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

  serviceAccount:
    create: true
    annotations: {}
    name: ""

lb:
  name: lb
  image:
    tag: "2.8.1"
    pullPolicy: Always
  replicaCount: 1

  podAnnotations: {}
  labels: {}
  podLabels: {}

  podSecurityContext: {}
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault

  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

  serviceAccount:
    create: true
    annotations: {}
    name: ""

  service:
    annotations: {}
    type: LoadBalancer
