# Default values for Codezero.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  tag: 2.6.0
hub:
  url: https://hub.codezero.io
space:
  token: ""
  name: ""
org:
  apikey: ""
  id: ""
opa:
  url: ""
  enabled: false

podAnnotations: { }
labels: { }
podLabels: { }

router:
  privilegedAccess: false

operator:
  # when true runs system and orchestrator in operator mode
  enabled: true

  name: operator
  image:
    tag: ""
    pullPolicy: Always
  replicaCount: 1

  podAnnotations: { }
  labels: { }
  podLabels: { }

  podSecurityContext: { }
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault

  nodeSelector: { }
  tolerations: [ ]
  affinity: { }

system:
  name: system
  image:
    tag: ""
    pullPolicy: Always
  replicaCount: 1

  podAnnotations: { }
  labels: { }
  podLabels: { }

  podSecurityContext: { }
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault

  resources: { }
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }

  serviceAccount:
    create: true
    annotations: { }
    name: ""

orchestrator:
  name: orchestrator
  image:
    tag: ""
    pullPolicy: Always
  replicaCount: 1

  podAnnotations: { }
  labels: { }
  podLabels: { }

  podSecurityContext: { }
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault

  resources: { }
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }


  serviceAccount:
    create: true
    annotations: { }
    name: ""

lb:
  name: lb
  image:
    tag: "2.8.1"
    pullPolicy: Always
  replicaCount: 1

  podAnnotations: { }
  labels: { }
  podLabels: { }

  podSecurityContext: { }
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault

  resources: { }
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }

  serviceAccount:
    create: true
    annotations: { }
    name: ""

  service:
    annotations: { }
    type: LoadBalancer
