apiVersion: v1
kind: Service
metadata:
  name: {{ include "spaceagent.name" . }}
  labels:
    {{- include "spaceagent.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8800
      targetPort: 8800
      protocol: TCP
      name: http
  selector:
    {{- include "spaceagent.selectorLabels" . | nindent 4 }}
