{{- if ne .Release.Namespace "codezero" }}
{{- fail "The codezero system has to be installed in codezero namespace" }}
{{- end }}


apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "system.fullname" . }}
  labels:
    {{- include "system.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "system.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "system.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "system.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: c6oio/czsystem:{{ .Values.sha | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CZ_SPACE_CA_CERT
              value: /etc/ssl/certs/space/ca.pem
            - name: CZ_SPACE_CERT
              value: /etc/ssl/certs/space/tls.pem
            - name: CZ_SPACE_CERT_KEY
              value: /etc/ssl/certs/space/tls.key
          envFrom:
            - secretRef:
                name: {{ include "system.fullname" . }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/ssl/certs/space
              name: space-cert
              readOnly: true
      volumes:
        - name: space-cert
          secret:
            secretName: space-cert
            optional: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
