apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}-crb
subjects:
- kind: ServiceAccount
  name: {{ include "system.serviceAccountName" . }} # name of your service account
  namespace: {{ .Release.Namespace }}
roleRef: # referring to your ClusterRole
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io