apiVersion: v1  
kind: Secret
metadata:
  name: {{ include "system.fullname" . }}
data:
  {{- if .Values.hubAPI }}
  TEAMSPACES_HUB_API: {{ .Values.hubAPI | b64enc }}
  {{- end }}
  {{- if .Values.token }}
  TEAMSPACES_HUB_SPACE_TOKEN: {{ .Values.token | b64enc }}
  {{- end }}