{{- if eq .Values.token "" }}
{{- fail "A Values.token is required" }}
{{- end }}

apiVersion: v1  
kind: Secret
metadata:
  name: {{ include "system.fullname" . }}
data:
  {{- if .Values.hubAPI }}
  TEAMSPACES_HUB_API: {{ .Values.hubAPI | b64enc }}
  {{- end }}
  TEAMSPACES_HUB_SPACE_TOKEN: {{ .Values.token | b64enc }}