
{{- define "codezero.spaceID" -}}
{{- $existingCM := lookup "v1" "ConfigMap" .Release.Namespace (include "codezero.name" .) -}}
{{- if $existingCM -}}
{{ $existingCM.data | toYaml }}
{{- else -}}
spaceID: ""
{{- end -}}
{{- end -}}


apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "codezero.name" . }}
data:
{{ include "codezero.spaceID" . | indent 2 -}}