
{{- if and (ne .Values.org.apikey "") (eq .Values.space.name "") (.Release.IsInstall) }}
{{- fail "A Values.space.name is required" }}
{{- end }}

{{- define "codezero.configmap" -}}
{{- $existingCM := lookup "v1" "ConfigMap" .Release.Namespace (include "codezero.name" .) -}}
{{- if $existingCM -}}
{{ $existingCM.data | toYaml }}
{{- else -}}
{{- if .Values.space.name }}
spaceName: {{ .Values.space.name }}
{{- end }}
spaceID: ""
{{- end -}}
{{- end -}}


apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "codezero.name" . }}
data:
{{ include "codezero.configmap" . | indent 2 -}}