apiVersion: v1
kind: Service
metadata:
  name: {{ include "codezero.fullname" . }}
  labels:
    {{- include "codezero.labels" . | nindent 4 }}
spec:
  type: {{ .Values.codezero.service.type }}
  ports:
    - port: 8800
      targetPort: 8800
      protocol: TCP
      name: system-http
    - port: 8901
      targetPort: 8901
      protocol: TCP
      name: orchestrator-https
  selector:
    {{- include "codezero.externalLBSelectorLabels" . | nindent 4 }}
