apiVersion: v1
kind: Service
metadata:
  name: {{ include "codezero.fullname" . }}
  labels:
    {{- include "codezero.labels" . | nindent 4 }}
spec:
  type: {{ .Values.codezero.service.type }}
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
      name: system
    - port: 8900
      targetPort: 8900
      protocol: TCP
      name: orchestrator
  selector:
    {{- include "codezero.externalLBSelectorLabels" . | nindent 4 }}
