apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "operator.name" . }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.operator.replicaCount }}
  selector:
    matchLabels:
      {{- include "operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "operator.podAnnotations" . | nindent 8 }}
      labels:
        {{- include "operator.podLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.operator.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ include "operator.name" . }}
        image: "c6oio/operator:{{ .Values.operator.image.tag | default .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
        command:
        - /operator
        args:
          - --leader-elect
          - --health-probe-bind-address=:8081        
        securityContext:
          {{- toYaml .Values.operator.securityContext | nindent 12 }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: operator
      terminationGracePeriodSeconds: 10
      {{- with .Values.operator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
