apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lb.name" . }}
  labels:
    {{- include "lb.labels" . | nindent 4 }}
data:
  haproxy.cfg: |
    global
      log stdout format raw local0
      maxconn 4096

    defaults
      log global
      timeout client 60s
      timeout connect 60s
      timeout server 60s

    frontend system
      bind :8800 ssl crt /etc/ssl/certs/space/server.pem
      default_backend system

    backend system
      server system system.codezero:8800 check
