apiVersion: v1
kind: Service
metadata:
  name: codezero
  labels:
    {{- include "lb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.lb.service.type }}
  ports:
    - port: 8800
      targetPort: 8800
      protocol: TCP
      name: system-http
    - port: 8900
      targetPort: 8900
      protocol: TCP
      name: orchestrator-http
  selector:
    {{- include "lb.selectorLabels" . | nindent 4 }}
