apiVersion: v1
kind: Service
metadata:
  name: {{ include "codezero.name" . }}
  labels:
    {{- include "lb.labels" . | nindent 4 }}
  annotations:
    {{ toYaml .Values.lb.service.annotations | indent 4 | trim}}
spec:
  type: {{ .Values.lb.service.type }}
  ports:
    - port: 8800
      targetPort: 8800
      protocol: TCP
      name: spaceagent-http
  selector:
    {{- include "lb.selectorLabels" . | nindent 4 }}
